### ISSUE TITLE
Outsource generic "readxl" table functions in own (new?) R package

### ISSUE THREAD

**Issue by mrustl** [mrustl/Testprojekt_01#6]
Proposed pkgname "kwb.readxl" (dedicated to "readxl")

**Comment by hsonne** [comment]
@mrustl I was just thinking about this. Suggestion of name? kwb.readxl?

**Comment by mrustl** [comment]
Removed from "GeoSalz" repo in commit: https://github.com/KWB-R/GeoSalz/commit/ebf75ff87c622cc6965b74f4d4df1c9468a69990 without breaking my R code

Now to be added by @hsonne  in R package "kwb-readxl" (https://github.com/kwb-r/kwb.readxl)
